---
- name: restart redmine
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - redmine
  notify:
    - restart nginx
 
- name: restart nginx
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
