production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: redmine
  pool: 10
  host: "{{ redmine_mysql_host }}"
  username: redmine
  password: "{{ redmine_redmine_mysql_password }}"
